### ISSUE TITLE
Project: Report for 20th May

### ISSUE THREAD

**Issue by fesiib** [temirrr/Priora#7]
Write a 1-2 page report of the project till 12PM Wed.

**Comment by fesiib** [comment]
@amanzholov8 @kunduzb17 @fesiib @temirrr 

Could you list below in the comments what you have already done? 

Also, we have to somewhat formalize our plans, so I suggest to write about them too.

**Comment by fesiib** [comment]
Have done:
1) Inspected the details of development and wrote a simple plugin for Jenkins;
2) Found similar and useful plugins for Jenkins that can be utilized;

In the process:
1) Investigating the structure of useful plugins;
2) Establishing comparison methods of the prioritization approach;
3) Looking for appropriate objectives to be given to the NSGA-II algorithm;
4) Trying to find specific details for plugin development;

I think:
1) We have to elaborate on our current architecture and add more details;
2) Come up with some rough plan of the development process;
- Maybe we have to try to draw a class diagram (do some CS350 stuff);
3) Plugin:
- Implementation
- Testing
- Comparison

**Comment by amanzholov8** [comment]
Have done:
1. Look through a couple of tutorials on Jenkins plugin implementation. (Did not fully understand how Jenkins plugins work, to be honest)
2. Search for ways how to measure the test time execution and result with Jenkins and JUnit. This article gives an interesting way of measuring these things: https://www.baeldung.com/junit-test-execution-time
3. Think about the differences between using Jenkins priority sorter plugin to set order and writing our own test ordering with JUnit. Conclusion: It seems to be better to write our own test ordering without using the priority sorter plugin. In case we use priority sorter plugin, separating each test case to jobs and ordering them might add substantial overhead. Usually, one job is created for the whole branch and it is considered good practice. So we could have a single job and order test cases within it by writing our own ordering.

**Comment by kunduzb17** [comment]
Have done:

1. Wrote basic structures for tests, chromosome, GA(except selection function, have some trouble with strategy).

In the process:

1. Selection function
2. Get suitable parameters
3. Test

**Comment by temirrr** [comment]
Have done:
- Studied about Jenkins pipeline syntax, cron syntax (doesn't work for us). 
- Studied about hooks. I think we will test locally to avoid network problems and non-determinism. So we won't use webhooks, but rather use local `post-commit` hook to trigger the pipeline execution. We will also need to add Git Plugin, which will be activated on commit trigger and do the job.
- Emailed Prof. There was no reply, so I emailed him again.
- Researched on benchmarking. Currently, I only have this: http://www.cs.ucr.edu/~gupta/teaching/206-12/project.html . Tried to play with one program in there.
In here, each program has several versions (each version has 1 fault). And each program has a lot of tests (1000-5000 tests for each program). So we can just write an automated script which runs all tests for a program with the given order. The only problem is that the **program and tests are in C**.  In that case, we would have to use smth else than JUnit. The tests are **independent**, since this is the benchmarking specifically for **test case prioritization** (but not regression testing though)
We can also look at some Java-programs, but automating the process of (Going to Github Repo + Switching Between Commits + Running Tests) is going to be very complex imo.

In the process:
- I want to write a Jenkins pipeline which will build a program and run tests today.

Next:
- Try to make the pipeline triggered by the post-commit hook.
- Please, send me other benchmark links to consider. I could find only that one, strangely.

**Comment by fesiib** [comment]
The Interim Report: https://docs.google.com/document/d/1eAsNUFq1-ImWnrTCS47z9Hlv8T_RA-8LjAdr_KkevwU/edit?usp=sharing
